SELECT distinct
--to_char("CreationTime", 'YYYY-MM') creationtime,
CASE WHEN "TemplateType" is null AND "TypeGenially" = 27 THEN '4.1-interactive-images'
WHEN "TemplateType" is null AND "TypeGenially" = 17 THEN '9.1-blank-creations'
--WHEN "TemplateType" is null AND "TypeGenially" = 18 THEN '9.2-ppt-importer'
WHEN "TemplateType" = 'template-presentation' THEN '1.1-template-presentation'
WHEN "TemplateType" = 'template-dossier' THEN '1.2-template-dossier'
WHEN "TemplateType" = 'template-reporting' THEN '1.3-template-reporting'
WHEN "TemplateType" = 'template-sales' THEN '1.4-template-sales'
WHEN "TemplateType" = 'template-horizontal-infographic' THEN '2.1-template-horizontal-infographic'
WHEN "TemplateType" = 'template-vertical-infographic' THEN '2.2-template-vertical-infographic'
WHEN "TemplateType" = 'template-diagrams' THEN '2.3-template-diagrams'
WHEN "TemplateType" = 'template-quiz' THEN '3.1-template-quiz'
WHEN "TemplateType" = 'template-games' THEN '3.2-template-games'
WHEN "TemplateType" = 'template-escape-room' THEN '3.3-template-escape-room'
WHEN "TemplateType" = 'template-video-presentation' THEN '5.1-template-video-presentation'
WHEN "TemplateType" = 'template-guide' THEN '6.1-template-guide'
WHEN "TemplateType" = 'template-didactic-unit' THEN '7.1-template-didactic-unit'
WHEN "TemplateType" = 'template-training-resources' THEN '7.2-template-training-resources'
WHEN "TemplateType" = 'template-personal-branding' THEN '8.1-template-personal-branding'
WHEN "TemplateType" = 'template-interactive-cards' THEN '8.2-template-interactive-cards'
WHEN "TemplateType" = 'template-post-h' THEN '8.3-template-post-h'
WHEN "TemplateType" = 'template-post-v' THEN '8.4-template-post-v'
WHEN "TemplateType" = 'template-post-s' THEN '8.5-template-post-s'
WHEN "TemplateType" is null THEN '9.91-no-template'
ELSE '9.92-others'
--ELSE (CASE WHEN "TemplateType" is not