steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud secrets versions access latest --secret="dbt-ci-profiles" > profiles.yml']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['deps']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['seed']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['run', '-x', '--exclude', 'metrics_login_activity+']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['test', '--exclude', 'metrics_login_activity+']

timeout: 1800s # 30 min
options:
  env:
  - 'PULL_REQUEST=$_PR_NUMBER'
  - 'DBT_PROFILES_DIR=/workspace'
