steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud secrets versions access latest --secret="dbt-prod-profiles" > profiles.yml']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['deps']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['seed']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['run', '--exclude', 'metrics_creator_activity+']

- name: 'gcr.io/cloud-builders/gcloud'
  dir: /workspace/deployments/prod
  entrypoint: 'bash'
  args: ['-c', './deploy_docs.sh']
  env:
  - COMMIT_SHA=$COMMIT_SHA

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['test', '--exclude', 'metrics_creator_activity+']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['run-operation', 'cleanup_dataset']

timeout: 1800s # 30 min
options:
  env:
  - 'DBT_PROFILES_DIR=/workspace'
