steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud secrets versions access latest --secret="dbt-prod-profiles" > profiles.yml']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['deps']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['seed']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['run']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['test']

- name: 'fishtownanalytics/dbt:0.21.0'
  args: ['run-operation', 'cleanup_dataset']

options:
  env:
  - 'DBT_PROFILES_DIR=/workspace'
